name: Update README with recent activity

on:
  schedule:
    - cron: '0 * * * *'   # update tiap jam
  workflow_dispatch:       # bisa dijalankan manual dari tab Actions

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update README
        uses: jamesgeorge007/github-activity-readme@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
